# Generated by Django 5.2.12 on 2026-06-16 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DifficultyLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("difficulty", models.CharField(max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "level_buy_price",
                    models.DecimalField(decimal_places=0, max_digits=10),
                ),
                (
                    "level_reward_price",
                    models.DecimalField(decimal_places=0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("inflation", "Inflation"), ("interest", "Interest")],
                        max_length=10,
                    ),
                ),
                ("is_positive", models.BooleanField(default=True)),
                ("rate", models.DecimalField(decimal_places=1, max_digits=11)),
                ("apply_time", models.DurationField()),
                ("executed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="items/")),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_balance",
                    models.DecimalField(decimal_places=2, default=1000, max_digits=14),
                ),
                (
                    "all_items_amounts",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_assets",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("is_bank", models.BooleanField(default=False)),
                (
                    "group",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_account",
                        to="groups.contestgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paid_amount", models.DecimalField(decimal_places=0, max_digits=10)),
                ("acquired_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_item",
                        to="bank.bankaccount",
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_item",
                        to="bank.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("bought", "Buy"), ("sold", "Sell")],
                        default="bought",
                        max_length=10,
                    ),
                ),
                ("action_time", models.DateTimeField(auto_now_add=True)),
                ("paid_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_item_trans",
                        to="bank.bankaccount",
                    ),
                ),
                (
                    "inflation_round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bank.event"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_item_trans",
                        to="bank.groupitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(default=0)),
                ("question_prompt", models.TextField()),
                ("answer", models.CharField(max_length=50)),
                (
                    "difficulty",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bank.difficultylevel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("group_answer", models.CharField(blank=True, max_length=50)),
                ("is_solved", models.BooleanField(default=False)),
                ("purchase_time", models.DateTimeField(auto_now_add=True)),
                ("receive_reward_time", models.DateTimeField(blank=True, null=True)),
                ("paid_amount", models.DecimalField(decimal_places=0, max_digits=10)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_question",
                        to="bank.bankaccount",
                    ),
                ),
                (
                    "buy_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bank.bankaccount",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_question",
                        to="bank.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consensual_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("otp", models.CharField(max_length=6, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("completed", "Completed"), ("pending", "Pending")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_buyer",
                        to="bank.bankaccount",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bank.question"
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_seller",
                        to="bank.bankaccount",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_bank", True)),
                fields=("is_bank",),
                name="only_one_bank_account",
            ),
        ),
    ]
