# Generated by Django 5.2.12 on 2026-06-16 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("contest", "Contest"),
                            ("group", "Group"),
                            ("personal", "Personal"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("invitation", "Invitation"),
                            ("otp", "Otp"),
                            ("bank-event", "Bank-Event"),
                        ],
                        max_length=15,
                    ),
                ),
                ("header", models.TextField()),
                ("message", models.TextField()),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profile",
                    ),
                ),
            ],
        ),
    ]
