# Generated by Django 5.2.12 on 2026-06-16 09:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bank", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeControl",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("duration", models.DurationField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not-started", "Not-Started"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("finished", "Finished"),
                        ],
                        default="not-started",
                        max_length=15,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("total_paused", models.DurationField(default=datetime.timedelta)),
                (
                    "current_inflation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bank.event",
                    ),
                ),
            ],
        ),
    ]
